# Generated by Django 2.2.5 on 2019-09-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favority',
            field=models.BooleanField(default=False),
        ),
    ]
