# Generated by Django 2.2.5 on 2019-09-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favority',
            new_name='is_favorite',
        ),
    ]
